name: Development CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/checkout@v7

      - name: Install .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore

      - name: Run automated tests
        run: dotnet test --no-build